version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-backend:
    depends_on:
      - mysqldb
    image: giovannibkn/tp-foyer:5.0.0  # Image backend
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "pwd",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

  app-frontend:
    image: giovannibkn/tp-foyer:5.0.0  # Image frontend
    restart: unless-stopped
    ports:
      - 8089:8089  # Port expos√© par l'application frontend
    environment:
      - API_URL=http://app-backend:8082/tpfoyer # URL de l'API backend

volumes:
  db :